// Auto-generated asset URLs from Vercel Blob
export const ASSET_URLS = {
  "amankhilani.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/amankhilani.jpg",
  "ku-star.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/ku-star.jpg",
  "driver-gaze.png": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/driver-gaze.png",
  "surge-lidar.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/surge-lidar.jpg",
  "robotics-rover.webp": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/robotics-rover.webp",
  "atlassian.png": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/atlassian.png",
  "antaragni.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/antaragni.jpg",
  "inter-iit.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/inter-iit.jpg",
  "film-club.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/film-club.jpg",
  "travel/Coldplay, Mumbai3.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Coldplay%2C%20Mumbai3.jpg",
  "travel/Goa1.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Goa1.jpg",
  "travel/Goa2.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Goa2.jpg",
  "travel/Goa3.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Goa3.jpg",
  "travel/Japan10.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Japan10.jpg",
  "travel/Japan11.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Japan11.jpg",
  "travel/Japan12.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Japan12.jpg",
  "travel/Japan13.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Japan13.jpg",
  "travel/Japan2.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Japan2.jpg",
  "travel/Japan3.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Japan3.jpg",
  "travel/Japan4.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Japan4.jpg",
  "travel/Japan5.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Japan5.jpg",
  "travel/Japan6.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Japan6.jpg",
  "travel/Japan7.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Japan7.jpg",
  "travel/Japan8.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Japan8.jpg",
  "travel/Japan9.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Japan9.jpg",
  "travel/Kasol, Himachal Pradesh1.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Kasol%2C%20Himachal%20Pradesh1.jpg",
  "travel/Kasol2.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Kasol2.jpg",
  "travel/Manali, Himachal Pradesh1.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Manali%2C%20Himachal%20Pradesh1.jpg",
  "travel/Manali2.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Manali2.jpg",
  "travel/Manali3.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Manali3.jpg",
  "travel/Mt. Fuji, Japan1.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Mt.%20Fuji%2C%20Japan1.jpg",
  "travel/Mumbai1.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Mumbai1.jpg",
  "travel/Mumbai2.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Mumbai2.jpg",
  "travel/Vietnam1.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Vietnam1.jpg",
  "travel/Vietnam2.jpg": "https://ktzsbwavlvswrknq.public.blob.vercel-storage.com/travel/Vietnam2.jpg"
};
